import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import toast from "react-hot-toast";
import { Activity, ArrowLeft, CalendarDays, CheckCircle2, Loader2, RefreshCcw, UsersRound } from "lucide-react";
import { assignAdminGroupTourStaff, confirmAdminGroupTour, getAdminGroupTourDetail, getAdminGroupTourTracking } from "../../api/bookingApi";
import { getAllStaff } from "../../api/staffApi";
import { Badge, formatDate, formatTime, getMeta, statusMeta } from "./bookingShared";

const groupStatusMeta = { WAITING: { label: "Đang ghép khách", className: "border-amber-200 bg-amber-50 text-amber-800" }, CONFIRMED: { label: "Đã xác nhận đoàn", className: "border-emerald-200 bg-emerald-50 text-emerald-800" }, IN_PROGRESS: { label: "Đang khởi hành", className: "border-sky-200 bg-sky-50 text-sky-800" }, COMPLETED: { label: "Đã hoàn thành", className: "border-slate-200 bg-slate-100 text-slate-700" }, CANCELLED: { label: "Không còn booking", className: "border-rose-200 bg-rose-50 text-rose-800" } };

export default function GroupTourDetailPage() {
  const { departureId } = useParams();
  const [tour, setTour] = useState(null), [tracking, setTracking] = useState(null), [staff, setStaff] = useState([]), [staffId, setStaffId] = useState(""), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false);
  const load = async () => { try { setLoading(true); const [detail, progress, employees] = await Promise.all([getAdminGroupTourDetail(departureId), getAdminGroupTourTracking(departureId), getAllStaff({ page: 0, size: 100, isActive: true })]); setTour(detail.data); setTracking(progress.data); setStaff(employees.data?.content || employees.data || []); setStaffId(detail.data.assignedStaffId ? String(detail.data.assignedStaffId) : ""); } catch (e) { toast.error(e?.response?.data?.message || "Không thể tải dữ liệu tour ghép"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [departureId]);
  useEffect(() => { if (!loading && window.location.hash === "#tracking") window.setTimeout(() => document.getElementById("tracking")?.scrollIntoView({ behavior: "smooth" }), 80); }, [loading]);
  const saveStaff = async () => { if (!staffId) return toast.error("Vui lòng chọn nhân viên phụ trách"); try { setBusy(true); const r = await assignAdminGroupTourStaff(departureId, Number(staffId)); setTour(r.data); toast.success("Đã lưu phân công"); } catch (e) { toast.error(e?.response?.data?.message || "Không thể phân công"); } finally { setBusy(false); } };
  const confirm = async () => { try { setBusy(true); const r = await confirmAdminGroupTour(departureId); setTour(r.data); toast.success("Đã xác nhận đoàn"); } catch (e) { toast.error(e?.response?.data?.message || "Không thể xác nhận đoàn"); } finally { setBusy(false); } };
  if (loading) return <div className="flex min-h-screen items-center justify-center"><Loader2 size={40} className="animate-spin text-emerald-600" /></div>;
  if (!tour || !tracking) return null;
  return <div className="min-h-screen bg-[#f8fafc] p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><Link to="/admin/group-tours" className="inline-flex items-center gap-2 font-black text-slate-600 hover:text-emerald-700"><ArrowLeft size={18}/> Quay lại danh sách</Link><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-sm font-black"><RefreshCcw size={17}/> Làm mới</button></div>
    <header className="rounded-3xl bg-slate-950 p-6 text-white"><div className="text-xs font-black uppercase tracking-widest text-emerald-300">Lịch ghép #{tour.departureId}</div><h1 className="mt-2 text-3xl font-black">{tour.tourName}</h1><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-3 py-2 font-bold"><CalendarDays size={15} className="mr-2 inline"/>{formatDate(tour.departureDate)} · {formatTime(tour.departureTime)}</span><Badge meta={getMeta(groupStatusMeta, tour.groupStatus)}/></div></header>
    <section className="mt-5 grid gap-4 sm:grid-cols-3"><Stat icon={<UsersRound/>} value={`${tour.occupiedPeople}/${tour.maxPeople}`} label="Khách đã giữ chỗ"/><Stat value={tour.bookingCount} label="Tổng đơn trong đoàn"/><Stat value={tour.availableSeats} label="Chỗ còn trống"/></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[1fr_340px]"><div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><h2 className="text-xl font-black">Các đơn trong tour ghép</h2><span className="text-sm font-bold text-slate-500">{tour.bookings?.length || 0} đơn</span></div><div className="overflow-x-auto"><table className="admin-responsive-table w-full text-left text-sm"><thead className="bg-slate-50 text-xs font-black uppercase text-slate-500"><tr><th className="px-4 py-3">Đơn</th><th className="px-4 py-3">Khách hàng</th><th className="px-4 py-3">Khách</th><th className="px-4 py-3">Trạng thái</th></tr></thead><tbody className="divide-y">{(tour.bookings || []).map(b => <tr key={b.id}><td className="px-4 py-3 font-black">{b.bookingCode}</td><td className="px-4 py-3"><div className="font-bold">{b.customerName}</div><div className="text-xs text-slate-500">{b.phone || b.email}</div></td><td className="px-4 py-3 font-black">{b.totalPeople || 0}</td><td className="px-4 py-3"><Badge meta={getMeta(statusMeta, b.status)}/></td></tr>)}</tbody></table></div></div><aside className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Quản lý đoàn</h2><p className="mt-2 text-sm font-semibold text-slate-500">Phân công nhân viên chung và xác nhận các đơn đang chờ.</p><select value={staffId} onChange={e=>setStaffId(e.target.value)} className="mt-5 h-12 w-full rounded-xl border px-3 font-bold"><option value="">Chọn nhân viên phụ trách</option>{staff.map(s=><option key={s.id} value={s.id}>{s.fullName}</option>)}</select>{tour.assignedStaffName && <div className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-900">Đang phụ trách: {tour.assignedStaffName}</div>}<button disabled={busy || !staffId} onClick={saveStaff} className="mt-4 w-full rounded-xl border border-emerald-300 px-4 py-3 font-black text-emerald-800 disabled:opacity-50">Lưu phân công</button><button disabled={busy || !tour.pendingBookingCount} onClick={confirm} className="mt-2 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 font-black text-white disabled:bg-slate-300"><CheckCircle2 size={17}/> Xác nhận đoàn</button></aside></section>
    <section id="tracking" className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xl font-black"><Activity size={21} className="text-emerald-700"/> Theo dõi lịch trình đoàn</h2><p className="mt-1 text-sm font-semibold text-slate-500">Theo dõi độc lập trong phạm vi tour ghép này.</p></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black text-slate-600">Tiến độ chung: {tracking.progressPercent || 0}%</span></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><Stat value={tracking.bookingsWithSchedule || 0} label="Đơn có lịch trình"/><Stat value={tracking.completedBookings || 0} label="Đơn hoàn thành"/><Stat value={tracking.needsReviewBookings || 0} label="Cần xem báo cáo"/><Stat value={`${tracking.completedActivities || 0}/${tracking.totalActivities || 0}`} label="Hoạt động hoàn thành"/></div><div className="mt-5 space-y-3">{(tracking.bookings || []).map(b => <div key={b.bookingId} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="font-black">{b.bookingCode} · {b.customerName}</div><Badge meta={getMeta(statusMeta, b.status)}/></div><div className="mt-2 text-xs font-semibold text-slate-500">{b.totalActivities ? `${b.completedActivities || 0}/${b.totalActivities} hoạt động · ${b.progressPercent || 0}%` : "Chưa có lịch trình hoạt động"}</div>{b.needsReview && <div className="mt-2 inline-flex rounded-full bg-amber-50 px-2.5 py-1 text-xs font-black text-amber-800">Cần admin xem lại</div>}</div>)}</div></section>
  </div></div>;
}

function Stat({ icon, value, label }) { return <div className="rounded-2xl bg-white p-5 shadow-sm">{icon && <span className="text-emerald-700">{icon}</span>}<div className="mt-3 text-3xl font-black">{value}</div><div className="text-sm font-bold text-slate-500">{label}</div></div>; }
